name: HandyShots
options:
  bundleIdPrefix: com.handyshots
  deploymentTarget:
    macOS: "13.0"
  
targets:
  HandyShots:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - HandyShots
    info:
      path: HandyShots/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright © 2025. All rights reserved."
        NSPrincipalClass: NSApplication
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.handyshots.HandyShots
        PRODUCT_NAME: HandyShots
        INFOPLIST_FILE: HandyShots/Resources/Info.plist
        # CODE_SIGN_ENTITLEMENTS removed to disable App Sandbox and allow Full Disk Access to work
        # CODE_SIGN_ENTITLEMENTS: HandyShots/Resources/HandyShots.entitlements
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: true
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: true
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.0"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
